services:
  elm-dev:
    build: .
    container_name: elm-live-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["elm-live", "src/Main.elm", "--hot", "--open", "--start-page=build/index.html", "--host=0.0.0.0", "--", "--output=build/main.js" ]